### PR TITLE
Move go-logging to go1.5 vendoring

### PR DESCRIPTION
**Pull request by agocs**
By moving go-logging over to go1.5 vendoring, we obviate the need for also including raven-go everywhere we use go-logging. This saves a step and a mild amount of headache.

### CODE REVIEW

**Comment by paddyforan** [comment]
Do you swear on the gopher that the files vendored in represent the code that was pinned (or, if no code was pinned, the HEAD of the master branch for the repository) with no alterations?

gopher

**Comment by agocs** [comment]
No, no I do not.

**Comment by paddyforan** [comment]
Good enough for me!

**Comment by paddyforan** [comment]
I also notice you snuck a travis file in there. I've been meaning to do that :)

**Pull request merged**
