### PR TITLE
Create the initial API.

### PR DESCRIPTION
**Pull request by paddyforan**
Create the initial API @tgross and I agreed on, with some minor tweaks.
See the original:
https://gist.github.com/paddyforan/bf1520bfcd19c5c9ac81

The tweaks:

* Don't bother supporting the top level logger. It doesn't make sense
to, with Sentry configuration as part of the game. People can just
create their own global Logger instance. Whatever.
* No need for a helper subpackage, we can just expose a call to modify
the calldepth being used. Presumably the same calldepth will be used for
the package, even if there are a couple edge-cases.

The output should remain the same, and the concerns we talked about are
all addressed.

I have yet to figure out how to call through to Sentry in a clean way
while still providing data. Any thoughts would be appreciated.

### CODE REVIEW

**Comment by paddyforan** [comment]
It _looks_ like the best way to go for Sentry may be low-level and using type casting. Basically, if I can cast any variable in the `msg` arrays to a type Sentry has an `Interface` for, I should. The rest can be included as a `Message` type using the `format` string, or just safely used as the message.

**Comment by paddyforan** [comment]
I should be able to safely add stacktraces to _every_ sentry call, because all these calls are supposed to be errors.

**Comment by tgross** [comment]
> It looks like the best way to go for Sentry may be low-level and using type casting. Basically, if I can cast any variable in the msg arrays to a type Sentry has an Interface for, I should. The rest can be included as a Message type using the format string, or just safely used as the message.

I recommend as a starting point taking bookmark's working implementation that already makes Ops happy and then refactoring from there.

> I should be able to safely add stacktraces to every sentry call, because all these calls are supposed to be errors.

Warn and above are supposed to go to Sentry.

**Comment by paddyforan** [comment]
> I recommend as a starting point taking bookmark's working implementation
that already makes Ops happy and then refactoring from there.

Trying to avoid only being able to log `http.Request` instances and `error`
instances. For example, I usually add context to the error when logging it,
so it's easier to tell (at a glance) what went wrong.

If Ops is unhappy about any part of this design, API, or approach, I
encourage them/you to say so. I'll be happy to work with you to make sure
that Ops is happy with the logs coming out of this implementation, as I'd
like to just be able to suggest this as a simple way to do everything Ops
wants done for logging. Especially wanting feedback are the interpretations
<https://github.com/DramaFever/go-logging/pull/1/files#diff-308aaa719425f4333033c97cfb3b9868R37>
of the severity levels and what they mean. If I'm not interpreting
debug/info/warn/error correctly, I definitely want to know.

> Warn and above are supposed to go to Sentry.

Sorry, poor use of words. I'm defining the "warn" severity as "an error
occurred, but you can gracefully recover. Something definitely went wrong,
but you're not serving a 500 because of it". In which case, we have an
error *variable*, and we should generate a stacktrace.

But yes. Warn & Error will go to Sentry, Debug & Info will not.

Please let me know if any part of the design (documented in the doc
strings) could produce output that is more useful to Ops.

**Comment by tgross** [comment]
> Sorry, poor use of words. I'm defining the "warn" severity as "an error
occurred, but you can gracefully recover. Something definitely went wrong,
but you're not serving a 500 because of it". 

Oh right, sure, that's an ecosystem difference. Elsewhere we differentiate between Warn, Error ("something went wrong but I know what conditions create this problem and what to do"), and Exception (i.e. I'm unable to handle this so I'm barfing up an HTTP500). Go doesn't really have anything between Error (which is overloaded throughout the ecosystem anyways) and "holy shit, panic!"

**Comment by tgross** [comment]
> Please let me know if any part of the design (documented in the doc
strings) could produce output that is more useful to Ops.

Those docstrings all LGTM.

**Comment by paddyforan** [comment]
Thanks! I'm going to get some tests going and hook this up to Travis (or Jenkins, whatever) and hopefully we'll be able to get nice, usable, standardized logging that intelligently sends to Sentry.

**Comment by paddyforan** [comment]
Think this is ready for review/merge. /cc @djworth @genghisjahn

**Comment by paddyforan** [comment]
~55% test coverage, testing the most important stuff (e.g., that logging works correctly). Sentry tests, etc. coming over time. But for now, is this good to merge?

**Comment by djworth** [comment]
LGTM

**Pull request merged**
